### ISSUE TITLE
Missing on a Mac: jinja2_time

### ISSUE THREAD

**Issue by ChristianKniep** [martisak/pandoc_conference_templates#4]
Hey there, when following your getting started guide I get this on my mac.
```
$ cookiecutter gl:martisak/paper-template
You've downloaded ${HOME}/.cookiecutters/paper-template before. Is it okay to delete and re-download it? [yes]: yes
Unable to load extension: No module named 'jinja2_time'
```

**Comment by martisak** [comment]
This seems related to the requirements for the cookie-cutter, which actually lists jinja2-time in the requirements.txt. https://gitlab.com/martisak/paper-template/-/blob/master/requirements.txt?ref_type=heads. However, there might have been a breaking change, see https://github.com/cookiecutter/cookiecutter/issues/1888.

I will close this issue and open a new on that project, see https://gitlab.com/martisak/paper-template/-/issues/2
